# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_seq', models.CharField(max_length=2000)),
                ('game_result', models.IntegerField(default=0)),
                ('game_duration', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_obj_id', models.CharField(max_length=200)),
                ('to_obj_id', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=200)),
                ('grid_size', models.IntegerField(default=0)),
                ('play_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=200)),
                ('exists', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=200)),
                ('feature', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=200)),
                ('play_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameRequest')),
            ],
        ),
        migrations.AddField(
            model_name='proposition',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Task'),
        ),
        migrations.AddField(
            model_name='interactions',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Task'),
        ),
    ]
