# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170929_0056'),
    ]

    operations = [
    ]
