# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170929_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='play_request',
        ),
        migrations.RemoveField(
            model_name='task',
            name='play_request',
        ),
    ]
