# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170929_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='from_obj_id',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='interactions',
            old_name='to_obj_id',
            new_name='obj_id',
        ),
    ]
