# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20171003_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequest',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='gamerequest',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Level'),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Task'),
        ),
    ]
