# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20171014_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='target_id',
            new_name='obj_id',
        ),
    ]
